// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcX7wWZfKV2RNYV7l-S0YPvgNloHpwVY',
    appId: '1:205658140405:web:1f7dde51696c998d301fbc',
    messagingSenderId: '205658140405',
    projectId: 'karsa-27c18',
    authDomain: 'karsa-27c18.firebaseapp.com',
    storageBucket: 'karsa-27c18.firebasestorage.app',
    measurementId: 'G-T4SD8L4XJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWY56wdbroHKArdB1zbLPpxdlf5lm4H8',
    appId: '1:205658140405:android:dced7142397a9858301fbc',
    messagingSenderId: '205658140405',
    projectId: 'karsa-27c18',
    storageBucket: 'karsa-27c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXgkXB-GJOo9gM9aYySW_P5KY0U-MFxI',
    appId: '1:205658140405:ios:48ac827791e908aa301fbc',
    messagingSenderId: '205658140405',
    projectId: 'karsa-27c18',
    storageBucket: 'karsa-27c18.firebasestorage.app',
    iosBundleId: 'com.example.kdkmpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXgkXB-GJOo9gM9aYySW_P5KY0U-MFxI',
    appId: '1:205658140405:ios:48ac827791e908aa301fbc',
    messagingSenderId: '205658140405',
    projectId: 'karsa-27c18',
    storageBucket: 'karsa-27c18.firebasestorage.app',
    iosBundleId: 'com.example.kdkmpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcX7wWZfKV2RNYV7l-S0YPvgNloHpwVY',
    appId: '1:205658140405:web:6090532e7e4c0bdb301fbc',
    messagingSenderId: '205658140405',
    projectId: 'karsa-27c18',
    authDomain: 'karsa-27c18.firebaseapp.com',
    storageBucket: 'karsa-27c18.firebasestorage.app',
    measurementId: 'G-V5LYXQ3JT1',
  );
}
